# Generated by Django 5.1.3 on 2024-11-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data_model',
            name='created_by',
        ),
    ]
